services:
  - type: web
    name: invoice-generator-backend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        fromDatabase:
          name: invoice-generator-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: RENDER_EXTERNAL_URL
        value: https://invoice-generator-backend.onrender.com
      - key: FRONTEND_URL
        value: https://invoice-genrator-ruddy.vercel.app

databases:
  - name: invoice-generator-db
    databaseName: invoice_generator
    user: invoice_generator_user
    plan: free
